kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: queueaicluster
nodes:
- role: control-plane
  extraPortMappings:
  # Map NodePort 30080 to host port 30080
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # Additional ports for other services if needed
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
